<?php

/**
 * @file
 * Contains mus.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mus module.
    case 'help.page.mus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module de test') . '</p>';
      return $output;

    default:
  }
}
